### ISSUE TITLE
push 2.0 to conda repositories?

### ISSUE THREAD

**Issue by jameslamb** [trevorld/r-argparse#29]
@trevorld thanks for this great package! I use it in a lot of my projects.

After debugging some build failures on [doppel-cli](https://github.com/jameslamb/doppel-cli/pull/122) tonight, I realized that the version of `argparse` available via `conda install` is far behind [CRAN](https://cran.r-project.org/web/packages/argparse/index.html).

![image](https://user-images.githubusercontent.com/7608904/58755610-eacc2700-84ac-11e9-917e-cc9e73daa44d.png)

Could you please push 2.0.1 to the `r` conda channel?

Thanks!

**Comment by trevorld** [comment]
I've never used conda nor have I ever packaged anything for conda.  It might be best to find and ask who previously put it to conda to update or since you seem to be an experienced conda user maybe you should update it yourself?  The big change in dependencies from 1.1.1 to 2.0.1 was dropping the R packages ``proto`` and ``getopt`` and adding the R package ``R6``.

**Comment by jameslamb** [comment]
Ha oh ok. I will do some detective work. I assumed that R packages that make it to `conda` are pushed there by their maintainers. It's wild that someone took your package and put it up there without you!

Please feel free to close this issue if this isn't something you're involved with. Would you like me to comment on it when I learn more, so you know who is distributing your package without your knowledge?

**Comment by trevorld** [comment]
I don't think it is that wild.  Aren't software packages for package managers like conda/apt/chocalatey/pacman/etc. often (usually?) maintained by someone other than the developer of the upstream package?  And aren't they often quite old because they are maintained by someone other than the developer?  For example my one R package in Debian (``optparse``) is also maintained by a user because it was a dependency of a piece of software he wanted to place in Debian.  I'd only assume that R packages on CRAN itself are maintained by the software developer and reasonably up-to-date (although the Github version is often even more up-to-date than the CRAN version!).

Feel free to comment with details if you'd like but I don't really need to know who put it up there.  The package license allows distribution without informing me so they haven't done anything wrong (and in fact I'm glad someone found enough value in my package to take the effort to share it with others).
