### ISSUE TITLE
how to deal too long option help info

### ISSUE THREAD

**Issue by felixlee0608** [trevorld/r-argparse#49]
<img width="1311" alt="image" src="https://github.com/trevorld/r-argparse/assets/33302799/344a177e-8063-47ed-8f29-372d6f00726b">

RT. 

how to change new line?

**Comment by trevorld** [comment]
In the future please make [a minimal reproducible example](https://posit.co/resources/videos/help-me-help-you-creating-reproducible-examples/) enclosed in a Github markdown

    ```r
    ```

block instead of a screenshot...

You could try to use another [argparse formatter](https://docs.python.org/3/library/argparse.html#formatter-class). In particular one could try `ArgumentParser(formatter_class="argparse.RawTextHelpFormatter)"` which "maintains whitespace for all sorts of help text, including argument descriptions."  You may need to manually enter a bunch of newlines and spaces where you want them but could give you the low-level formatting control you want.

If you switch from `{argparse}` to `{optparse}` then it is possible to write you own custom help formatter in R.
